Module: Demo.EventBus
Version: 1.0-DEV
Description: Module description
Pragmas:
  - Overrides:
      Module::WebSocket.RouteSelectionExpression: $request.body.Action
Items:

  - Function: WebSocketListenerFunction
    Memory: 256
    Timeout: 30
    Sources:
      - WebSocket: $connect
        Invoke: OpenConnection

      - WebSocket: $disconnect
        Invoke: CloseConnection

      - WebSocket: subscribe
        Invoke: SubscribeRequest

      - WebSocket: unsubscribe
        Invoke: UnsubscribeRequest

  - Resource: DataTable
    Scope: all
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S

        - AttributeName: SK
          AttributeType: S

        - AttributeName: GS1PK
          AttributeType: S

        - AttributeName: GS1SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH

        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: GS1
          KeySchema:
            - AttributeName: GS1PK
              KeyType: HASH

            - AttributeName: GS1SK
              KeyType: RANGE

          Projection:
            ProjectionType: ALL

  - Function: EventBroadcastFunction
    Scope: WebSocketListenerFunction
    Memory: 256
    Timeout: 30

  - Resource: EventTopic
    Scope: WebSocketListenerFunction
    Type: AWS::SNS::Topic
    Allow:
      - sns:Subscribe
      - sns:Unsubscribe

  - Resource: EventBroadcastPermission
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EventBroadcastFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref EventTopic
