Module: Demo.EventBus
Version: 1.0-DEV
Description: Module description
Pragmas:
  - Overrides:
      Module::WebSocket.RouteSelectionExpression: $request.body.Action
Items:

  - Function: WebSocketListenerFunction
    Description: Lambda function listening on the WebSocket connection
    Memory: 256
    Timeout: 30
    Sources:
      - WebSocket: $connect
        Invoke: OpenConnection

      - WebSocket: $disconnect
        Invoke: CloseConnection

      - WebSocket: Hello
        Invoke: Hello

      - WebSocket: Subscribe
        Invoke: Subscribe

      - WebSocket: Unsubscribe
        Invoke: Unsubscribe

  - Resource: DataTable
    Description: DynamoDB table for storing webSocket connection information and CloudWatch event rules
    Scope:
      - WebSocketListenerFunction
      - EventBroadcastFunction
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S

        - AttributeName: SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH

        - AttributeName: SK
          KeyType: RANGE

  - Function: EventBroadcastFunction
    Description: Lambda function for broadcasting CloudWatch events to a WebSocket connection
    Memory: 256
    Timeout: 30
    Properties:
      Environment:
        Variables:
          DEBUG_LOGGING_ENABLED: true

  - Resource: EventTopic
    Description: SNS topic for fan-out invocation on all open WebSocket connections
    Scope:
      - WebSocketListenerFunction
      - EventBroadcastFunction
    Type: AWS::SNS::Topic
    Allow:
      - sns:Subscribe
      - sns:Unsubscribe

  - Resource: KeepAliveRule
    Description: CloudWatch schedule rule for regularly sending a keep-alive message on each open WebSocket connection
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 minute)
      Targets:
        - Id: EventTopic
          Arn: !Ref EventTopic

  - Variable: KeepAliveRuleArn
    Description: ARN for CloudWatch schedule rule used to differentiate between keep-alive message and other scheduled events
    Scope: EventBroadcastFunction
    Value: !GetAtt KeepAliveRule.Arn

  - Variable: HttpApiInvocationToken
    Description: Token used to restrict invocations of the HTTP API
    Scope:
      - WebSocketListenerFunction
      - EventBroadcastFunction
    Value:
      Fn::Base64: !Select [ 2, !Split [ "/", !Ref AWS::StackId ]]

  - Resource: KeepAliveRulePolicy
    Description: SNS topic policy to allow keep-alive schedule rule to invoke the event topic
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EventsPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref EventTopic
      Topics:
        - !Ref EventTopic

  - Resource: EventBroadcastPermission
    Description: Lambda permission to allow HTTP API to invoke broadcast function
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EventBroadcastFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${EventBroadcastApi}/*/$default"

  - Resource: EventBroadcastApi
    Description: HTTP API used for SNS topic subscriptions to broadcast across all open WebSocket connections
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${Module::Id}-HttpApi"
      Description: Event Broadcast HTTP API
      ProtocolType: HTTP
      Target: !GetAtt  EventBroadcastFunction.Arn

  - Variable: EventBroadcastApiUrl
    Scope: WebSocketListenerFunction
    Description: HTTP API endpoint for broadcasting events
    Value: !Sub "${EventBroadcastApi.ApiEndpoint}/$default"